version: '3'

networks:
  app-searchcep:
    driver: bridge

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app-searchcep
  web:
    image: php:7.2.2-apache
    container_name: php_web_viacep
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true